services:
  - type: web
    name: anime-guess
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: DATABASE_URL
        sync: false
    scaling:
      minInstances: 1
      maxInstances: 1
